### ISSUE TITLE
Having trouble with implementing arithmetic operation because of my system

### ISSUE THREAD

**Issue by yiwenchen1999** [fsareshwala/cs404.1#7]
Hi, because I use a Windows laptop with Ubuntu subsystem, and Windows add \r\n for a change of line instead of \n in Linux, I am having problem outputting any arithmetic operation under Linux unless I change the syntax from var to  $ { var // $ '\r' } when doing echo
The error will not occur if I am running under git bash, which is under Windows.
Should I change the syntax? Or is it OK to keep it the normal way and not operate under Linux?

**Comment by fsareshwala** [comment]
Yiwen,

Whichever editor you are using most likely will allow you to save files with Unix line endings (`\n`) instead of Windows line endings (`\r\n`). Search your editor settings for such a feature and once you enable it you should be able to save files correctly so that it works. Let me know how that goes for you.

Lastly, please post class questions on campuswire rather than in GitHub issues so that other class members can participate as well.

If you continue to have issues with this, please use campuswire.
